apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-app.fullname" . }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  selector:
    app: {{ include "fastapi-app.name" . }}
